version: '3'
services:
  postgres:
    image: postgres:11-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .compose-data/postgresql:/var/lib/postgresql/data/pgdata

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
      REDIS_URL: $REDIS_URL
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      WEBHOOK_SECRET: $WEBHOOK_SECRET
      PRIVATE_KEY: $PRIVATE_KEY
      OAUTH_SECRET: $OAUTH_SECRET
      GITHUB_ACCESS_TOKEN: $GITHUB_ACCESS_TOKEN
    restart: on-failure
    expose:
      - "3000"

  worker:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
      REDIS_URL: $REDIS_URL
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      WEBHOOK_SECRET: $WEBHOOK_SECRET
      PRIVATE_KEY: $PRIVATE_KEY
      OAUTH_SECRET: $OAUTH_SECRET
      GITHUB_ACCESS_TOKEN: $GITHUB_ACCESS_TOKEN
    restart: on-failure
    command: bundle exec sidekiq -C config/sidekiq.yml

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
