default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: shipit_development

test:
  <<: *default
  database: shipit_test

production:
  <<: *default
  database: shipit_production
  primary:
    <<: *default
    database: shipit_production
  queue:
    <<: *default
    database: shipit_production
    migrations_paths: db/queue_migrate
